<?php

namespace AppBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbTicketPerDay($dateOfVisit)
    {
        $qb = $this->createQueryBuilder('b')
            ->innerJoin('b.tickets', 't')
            ->addSelect('t')
            ->select('COUNT(t.id)')
            ->where('b.dateOfVisit = :dateOfVisit')
            ->setParameter('dateOfVisit', $dateOfVisit);

        return (int) $qb->getQuery()->getSingleScalarResult(); // Cast for result = int
    }
}
